blank_issues_enabled: false
contact_links:
  - name: Gatsby Documentation
    url: https://www.gatsbyjs.org/docs/
    about: Check out the Gatsby documentation for answers to common questions
  - name: Gatsby Discord
    url: http://gatsby.dev/discord
    about: Ask general questions about Gatsby that are not related to these themes
